name: sudoku
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - cudatoolkit=10.2.89=h74a9793_1
  - freetype=2.10.2=hd328e21_0
  - hdf5=1.10.4=nompi_hcc15c50_1106
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2020.1=216
  - jpeg=9b=hb83a4c4_2
  - libopencv=4.0.1=hbb9e17c_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=h62dcd97_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.1.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - ninja=1.9.0=py38h74a9793_0
  - numpy=1.18.5=py38h6530119_0
  - numpy-base=1.18.5=py38hc3f5095_0
  - olefile=0.46=py_0
  - opencv=4.0.1=py38h2a7c758_0
  - openssl=1.1.1g=he774522_0
  - pillow=7.2.0=py38hcc1f983_0
  - pip=20.1.1=py38_1
  - py-opencv=4.0.1=py38he44ac1e_0
  - python=3.8.3=he1778fa_2
  - python_abi=3.8=1_cp38
  - pytorch=1.5.1=py3.8_cuda102_cudnn7_0
  - scipy=1.5.0=py38h9439919_0
  - setuptools=45.2.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h2a8f88b_0
  - tk=8.6.10=he774522_0
  - torchvision=0.6.1=py38_cu102
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.34.2=py38_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.4=ha9fde0e_3
